### ISSUE TITLE
badly chosen npm package name

### ISSUE THREAD

**Issue by trollkotze** [disjukr/croquis.js#16]
This looks nice. But if I If I yarn install and try to import stuff from this npm package, I get:

```
Cannot find module 'croquis.js' or its corresponding type declarations.
```
That's because the TypeScript compiler apparently concludes the `.js` ending that it should import from a the file `./croquis.js` in the current directory.

**Comment by disjukr** [comment]
Ok. I published it with another name(`@disjukr/croquis-js`).
