### ISSUE TITLE
reboot

### ISSUE THREAD

**Issue by disjukr** [disjukr/croquis.js#3]
reboot 이전 커밋: 0b8d857cfb45725fb2c6e9eb74f765dde4c3f10c

~jquery based로 다시 작성.~

고려해야할 부분:
- `iframe`으로 샌드박싱
- api 모양새 - 어차피 `canvas`를 사용하므로 es5 feature를 마음껏 사용할 수 있다
- 타블렛 - 지금은 필압만 받을 수 있게 돼있는데 기울기 정보도 활용할 수 있게끔
- stabilizer - 보정 속성이 많아질 수록 연산량에 부담이.. 크게 신경쓸 정도는 아니지만
- 레이어 유저 커스텀 속성(레이어 이름 등)
- 지우개 - css나 svg같은걸론 해결 안되므로 `setInterval` 트릭을 써야한다.
- history - undo, redo 구현. 그리기 명령을 트래킹할지는 약간 고민되는데.. undo에는 어차피 dirty rectangle이 필수라 이미 결정된 걸지도. 어떻게 하면 히스토리를 유연하게 만들 수 있을까.. 메모리 처먹는 것 문제는 local storage를 활용하는 것도 생각 중.
- 캐싱 - eyedropper 마냥 픽셀을 여러번 참조해야하는 경우 image data를 그때그때 얻어쓰면 gpu메모리랑 왔다갔다 하는 비용이 워낙 크기 때문에 캐싱이 필요함.
- 문서화
- webgl? - 학습비용이 높고 ie10이하 포기해야함. 대신 여러가지 hack들을 쓸 필요가 전부 사라지고 블렌딩 모드도 구현 가능해진다.

**Comment by webhacking** [comment]
:feelsgood:
