### ISSUE TITLE
더 이상 개발 안 하시나요? 

### ISSUE THREAD

**Issue by easylogic** [disjukr/croquis.js#8]

**Comment by disjukr** [comment]
마침 최근에 다시 이 프로젝트를 손보던 중이었어요.

작업중인 내용은 `2020` 브랜치에서 확인하실 수 있습니다: https://github.com/disjukr/croquis.js/tree/2020

혹시 라이브러리 사용과 관련해서 궁금하신게 있다면 [트위터](https://twitter.com/disjukr) DM이나 디스코드(0xABCDEF#2702)로 연락 주세요.

**Comment by disjukr** [comment]
이 이슈는 2020 브랜치를 master에 머지한 다음 닫겠습니다.
